apiVersion: apps/v1
kind: Deployment

metadata:
  name: cartservice
  namespace: ksana

spec:

  replicas: 1

  selector:
    matchLabels:
      app: cartservice

  template:

    metadata:

      labels:
        app: cartservice

    spec:

   

      terminationGracePeriodSeconds: 30

      containers:

      - name: cartservice

        image: ksana_service-cartservice:latest

        imagePullPolicy: IfNotPresent

        ports:

        - containerPort: 8763

        envFrom:

        - configMapRef:
            name: common-config

        - configMapRef:
            name: cartservice-config

        - secretRef:
            name: cartservice-secret

        resources:

          requests:
            cpu: "250m"
            memory: "512Mi"

          limits:
            cpu: "1000m"
            memory: "1Gi"

        readinessProbe:

          httpGet:
            path: /actuator/health
            port: 8763

          initialDelaySeconds: 60
          periodSeconds: 15

        livenessProbe:

          httpGet:
            path: /actuator/health
            port: 8763

          initialDelaySeconds: 120
          periodSeconds: 30