spring:
  application:
    name: apigateway

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://configserver:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
