apiVersion: v1
kind: Secret

metadata:
  name: authservice-secret
  namespace: ksana

type: Opaque

stringData:

  SPRING_DATASOURCE_PASSWORD: auth_password

  JWT_SECRET: ksana-grocery-authentication-jwt-secret-key-2026