apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: ksana

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:

      containers:

      - name: postgres

        image: postgres:16

        ports:
        - containerPort: 5432

        envFrom:

        - configMapRef:
            name: postgres-config

        - secretRef:
            name: postgres-secret

        volumeMounts:

        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:

      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

      - name: initdb
        configMap:
          name: postgres-initdb