apiVersion: v1
kind: ConfigMap

metadata:
  name: apigateway-config
  namespace: ksana

data:

  SERVER_PORT: "9090"

  SPRING_APPLICATION_NAME: apigateway

  CONFIG_SERVER_URL: http://configserver:8888

  EUREKA_URL: http://admin:admin123@discoveryservice:8761/eureka/

  SPRING_PROFILES_ACTIVE: kubernetes